### ISSUE TITLE
How to specify the size of the view controller?

### ISSUE THREAD

**Issue by onmyway133** [justeat/ScrollingStackViewController#1]
Hi, interesting approach. You didn't mention the size of the view controller? Do we need to specify the size of the view controller beforehand? And how to change the size dynamically?

Sorry for so many questions 😇

**Comment by maciejtrybilo** [comment]
No worries. The view controller's root view should have enough constraints to self size vertically. Then it should all just work. This is a little painful if you use IB as it doesn't support top level self sizing views, but it does work live.
