### ISSUE TITLE
Add method: setViewController(viewController: UIViewController, hidden: Bool)

### ISSUE THREAD

**Issue by richardtop** [justeat/ScrollingStackViewController#28]
Add method: setViewController(viewController: UIViewController, hidden: Bool)

Without this method, I'm required to check the value of the bool and dynamically dispatch the method:

```Swift
observedProperty.observe { isHidden in
if isHidden {
stackViewController.hide(vc)
} else {
stackViewController.show(vc)
}
```

With the method I propose implemented, it becomes as simple as:

```Swift
observedProperty.observe { isHidden in
stackViewController.set(viewController: vc, hidden: isHidden)
}
```

Related #27

**Comment by ghost** [comment]
Good point. I'm going to open a PR with it.
