### ISSUE TITLE
Support for disabling animation completely

### ISSUE THREAD

**Issue by richardtop** [justeat/ScrollingStackViewController#29]
I'd like this library to have support for disabling animations completely either via a parameter (i.e. `animated: Bool`) or via a property on the `ScrollingStackViewController.`

Currently, I have to pass a custom animation function on initialization which is error-prone:
```Swift
    private lazy var stackViewController: ScrollingStackViewController = {
        func noAnimation(_ animations: @escaping () -> (), completion: ((Bool) -> Void)?) {
            animations()
            completion?(true)
        }
        let controller = ScrollingStackViewController()
        controller.scrollView.delaysContentTouches = false
        controller.animate = noAnimation
        return controller
    }()

```

**Comment by gigisommo** [comment]
Thank you for sharing this. I was already thinking about adding an `animated` boolean to each function that performs an animation like UIKit does in the presentation functions for the view controller. What do you think about that?

**Comment by richardtop** [comment]
Great idea. I think, it's best to have this control behave similar to the other UIKit components. Would be great, if it could ignore animations if wrapped in "performWithoutAnimations" block.

The "animated" property is the way to go.

**Comment by gigisommo** [comment]
@richardtop could you review the PR that I opened? https://github.com/justeat/ScrollingStackViewController/pull/30 I think that this should address this issue and improve the management of the hidden state as you asked in the [issue 28](https://github.com/justeat/ScrollingStackViewController/issues/28)
