### ISSUE TITLE
Can I have scrollview inside one of the viewController?

### ISSUE THREAD

**Issue by santhoshs55** [justeat/ScrollingStackViewController#31]
Does it support scrolling inside a childviewController separately?

Assume I have a parent viewController with two childVC and one of top childVC should be scrollable and once its scroll ends it should continue to scroll the second one.

is it possible?

**Comment by gigisommo** [comment]
It should be possible, but the issue of a scrollview inside a scrollview is not managed by the `ScrollingStackViewController`. It should be up to yours view controller to manage it.
You should constraint the height of the child view controller in this way it is not going to expand entirely and it will allow you to scroll in the child view controller's scrollview. This class does not assume any behavior of the child view controllers, so it should be up to them to manage it. 
The only issue that I see is that I can see is that the scrollview inside the view controller will get the touches anyway, the workaround could be to disable the `userInteraction` on the scrollview, but this will make the scrollview impossible to scroll up also.
Let us know if you need further explanations or help.
