### ISSUE TITLE
Observe "isHidden" property of the child controller's view

### ISSUE THREAD

**Issue by richardtop** [justeat/ScrollingStackViewController#33]
Reopening #27 

Everything works fine when adding a child controller without insets.
However, when using non-zero edge insets, it's impossible to use the `isHidden` property of the child's view to hide and show the controller.

This method doesn't work because the container view is always visible, regardless of the parent. 

I propose observe `isHidden` property and always sync it with the container view, so that the ScrollingStackViewController's behavior is consistent, regardless of the way child has been added.

This feature would be great to have to allow controllers automatically show or hide themselves, or to use reactive UIKit bindings with one of the popular frameworks (ReactiveCocoa, RxSwift, Bond, etc), so the potential is truly limitless ✌️

**Comment by albertodebortoli** [comment]
Hi @richardtop, I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.
