### ISSUE TITLE
Cannot implement UIPageviewcontroller into the ScrollingStackViewController

### ISSUE THREAD

**Issue by kamenr** [justeat/ScrollingStackViewController#9]
Hi all,

I have a UIPageviewcontroller created with 2 other controllers. When I add this UIpageviewcontroller into the ScrollingStackViewController it failed to display the UIpageview, its there anyway can add in UIpageviewcontroller ? Thanks

**Comment by ghost** [comment]
Hi @kamenr, we never explicitly supported UIPageViewController or other container view controllers to work within a ScrollingStackViewController. 
This [line](https://github.com/justeat/ScrollingStackViewController/blob/master/ScrollingStackViewController/Classes/ScrollingStackViewController.swift#L185) grabs the view of the provided view controller, adds it to another view and ultimately insert the latter in the stack view.
We are sorry, but unfortunately there is simply no support for container view controllers with the current implementation.

**Comment by kamenr** [comment]
Noted Albert, thanks for the feedback
